#!/bin/sh

info=$(nmcli device show wlp1s0)
state=$( echo "${info}" | grep 'STATE' | tr -s " " | cut -d " " -f3)

[ "$state" = "(unavailable)" ] && exit;
strength=$( echo "${info}" | grep 'STATE' | tr -s " " | cut -d " " -f2)
SSID=$( echo "${info}" | grep 'CONNECTION' | tr -s " " | cut -d " " -f2)

[ "${state}" = "(connected)" ] && echo " ${strength} 󰤨 ${SSID} " || echo " 󰤯 "
