#!/bin/sh

[ "$(bluetoothctl show 68:54:5A:1A:0A:0D | grep 'Powered:' | cut -d ' ' -f2)" = "no" ] && exit;

if [ "$(bluetoothctl info)" != "Missing device address argument" ]; then
    icon="󰂰 "
    N=$(bluetoothctl info|grep "Name" | cut -d " " -f2-9 | head -c 4 | tr -d ":space:"); name="${N}..."
else
    icon="󰂯"
fi
printf "%s" " $icon$name "
