#!/bin/sh

[ "$(bluetoothctl show 68:54:5A:1A:0A:0D | grep 'Powered:' | cut -d ' ' -f2)" = "no" ] && exit;

info=$(bluetoothctl info)
if [ "${info}" = "Missing device address argument" ]; then
    printf " 󰂯 "
else
    name=$( echo "$info" | grep "Name" | cut -d " " -f2-9 | head -c4 | awk '{$1=$1};1' )
    printf " 󰂰 %s... " "$name"
fi
