#!/bin/sh

killall -q xidlehook

xidlehook --detect-sleep --not-when-audio \
 --not-when-fullscreen --timer 300 'backlight_control 50%' 'backlight_control 100%' \
 --timer 60 'slock backlight_control 100%' - \
 --timer 540 'systemctl suspend' - & 
