#!/bin/sh

pkill xidlehook > /dev/null 2>&1

xidlehook --detect-sleep --not-when-audio \
 --not-when-fullscreen --timer 300 'light -S 50' 'light -S 100' \
 --timer 600 'light -S 100; slock' - \
 --timer 540 'systemctl suspend' - & 
