#!/bin/sh

selection="$(printf 'Cancel\nShutdown\nReboot\nSuspend' | dmenu -c -l 4 -h 28 -fn Dejavu-12 -bw 2)"
if [ "$selection" = 'Shutdown' ]
then
	shutdown -h now
elif [ "$selection" = 'Reboot' ]
then
	reboot
elif [ "$selection" = 'Suspend' ]
then
    zzz
fi
