#!/bin/sh

selection="$(echo -e '0. Cancel\n1. Shutdown\n2. Reboot\n3. Suspend' | dmenu -c -l 4 -h 28 -fn Dejavu-12 -bw 2 | awk '{print $2}')"
if [ "$selection" == 'Shutdown' ]
then
	shutdown now
elif [ "$selection" == 'Reboot' ]
then
	reboot
elif [ "$selection" == 'Suspend' ]
then
	systemctl suspend
fi
